version: '2'

services:
    php:
        build: php7-fpm
        ports:
            - 9000:9000
        volumes:
            - api:/var/www/lagen-api
    nginx:
        build: nginx
        ports:
            - 4242:80
            - 4243:81
        links:
            - php
        volumes:
            - api:/var/www/lagen-api
volumes:
    api:
