version: '2'

services:
    lagen:
        image: nginx
        build:
            context: nginx
            args:
                jwt_passphrase: "mypassphrase"
                allowed_origins: "http://lagen.mydomain.com"
                user: "myuser"
                password: "mypassword"
        ports:
            - 4242:80
            - 4243:81
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
